import type { Config } from 'tailwindcss'

// AUTO-GENERATED by scripts/gen-tokens.ts — do not edit directly
// Edit brand.config.ts then run: pnpm brand:gen

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
        '100': '#f3f6f7',
        '200': '#e1ebf0',
        '300': '#c1dfeb',
        '400': '#88ceed',
        '500': '#079edf',
        '600': '#0b98d5',
        '700': '#0d74a0',
        '800': '#0d506d',
        '900': '#0c2d3c'
        },
        'brand-secondary': {
        '100': '#f4f3f7',
        '200': '#e5e1f0',
        '300': '#cec1eb',
        '400': '#a688ed',
        '500': '#4807df',
        '600': '#480bd5',
        '700': '#3a0da0',
        '800': '#2a0d6d',
        '900': '#1a0c3c'
        },
        gray: {
        '100': '#f7f7f7',
        '200': '#ededed',
        '300': '#dbdbdc',
        '400': '#bcbdbe',
        '500': '#929596',
        '600': '#6f7172',
        '700': '#565758',
        '800': '#3a3b3b',
        '900': '#212121'
        },
        positive: {
        '100': '#f4f6f4',
        '200': '#e4ece5',
        '300': '#cbe1cd',
        '400': '#9fd5a5',
        '500': '#36a342',
        '600': '#3aa646',
        '700': '#307e38',
        '800': '#235729',
        '900': '#17311a'
        },
        negative: {
        '100': '#f6f3f3',
        '200': '#eee3e2',
        '300': '#e7c7c5',
        '400': '#e39591',
        '500': '#e43c33',
        '600': '#c3261e',
        '700': '#92211b',
        '800': '#651a16',
        '900': '#371210'
        },
        notice: {
        '100': '#f7f4f3',
        '200': '#f0e4e0',
        '300': '#eccbc1',
        '400': '#eda087',
        '500': '#fb8a65',
        '600': '#d63c0a',
        '700': '#a1310d',
        '800': '#6e240c',
        '900': '#3c170b'
        },
      },
      fontFamily: {
        sans: ["Inter","sans-serif"],
      },
      fontSize: {
        'heading1': ['22px', { lineHeight: '30.5px', letterSpacing: '-0.2px', fontWeight: '700' }],
        'heading2': ['19px', { lineHeight: 'normal', letterSpacing: '-0.2px', fontWeight: '700' }],
        'heading3': ['17px', { lineHeight: 'normal', letterSpacing: '-0.2px', fontWeight: '700' }],
        'body1': ['17px', { lineHeight: '24px', letterSpacing: '-0.4px', fontWeight: '400' }],
        'body2': ['15px', { lineHeight: '21.45px', fontWeight: '400' }],
        'body3': ['13.8px', { lineHeight: '20px', fontWeight: '400' }],
        'caption1': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'caption2': ['12.3px', { lineHeight: '18.45px', fontWeight: '400' }]
      },
      borderRadius: {
        DEFAULT: '8px',
        sm:      '4px',
        md:      '8px',
        lg:      '16px',
        full:    '9999px',
      },
      spacing: {
    '0': '0.000rem',
    '1': '0.313rem',
    '2': '0.625rem',
    '4': '1.250rem',
    '6': '1.875rem',
    '8': '2.500rem',
    '10': '3.125rem',
    '12': '3.750rem',
    '16': '5.000rem',
    '20': '6.250rem',
    '24': '7.500rem',
    '32': '10.000rem',
    '40': '12.500rem',
    '48': '15.000rem',
    '64': '20.000rem',
    '80': '25.000rem',
    '96': '30.000rem'
      },
      transitionDuration: {
        DEFAULT: '200ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        spring:  'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      boxShadow: {
        sm:   '0 1px 8px rgba(0,0,0,0.06)',
        DEFAULT: '0 4px 20px rgba(0,0,0,0.08)',
        md:   '0 4px 20px rgba(0,0,0,0.08)',
        lg:   '0 8px 40px rgba(0,0,0,0.10)',
      },
    },
  },
  plugins: [],
}

export default config
